services:
  simpleapi:
    build:
      context: .
    ports:
      - "8080:8080"
    restart: unless-stopped
    init: true
    # env_file: ./.env  # Uncomment if .env file exists
    depends_on: [ ]
networks:
  default:
    name: simpleapi_network