version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=simpleapi
    ports:
      - "5432:5432"
  ibm-mq:
    image: ibmcom/mq
    container_name: ibm-mq
    ports:
      - "1414:1414"  # MQ listener port
      - "9443:9443"  # Web console
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
      - MQ_APP_PASSWORD=passw0rd
      - MQ_ADMIN_PASSWORD=admin123
      - MQ_ENABLE_METRICS=true
      - MQ_HOST=ibm-mq
      - MQ_PORT=1414
      - MQ_QMGR=QM1
      - MQ_CHANNEL=DEV.ADMIN.SVRCONN  # Changed to match config.mqsc
      - MQ_USER=admin  # Changed to match the MCA user in config.mqsc
      # Optional: Create additional queues on startup
      - MQ_DEV=true  # Enables development default configuration
    volumes:
      - mq-data:/var/mqm  # Persistent storage for queue data
      # Optional: Mount custom MQ configuration
      - ./config.mqsc:/etc/mqm/config.mqsc
    healthcheck:
      test: [ "CMD", "bash", "-c", "dspmq -m QM1 | grep Running" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 40s

volumes:
  mq-data:
    name: ibm-mq-data