version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simpleapi
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - app-network
    depends_on:
      - auth-server

  auth-server:
    image: maxiplux/simpleapi-authorization-and-resource-server:1.0.0
    container_name: auth-server
    ports:
      - "9000:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
